#Đây là tên của workflow, bạn có thể đặt tên khác nếu muốn
name: Deploy to AWS EC2

on:
  push:
    braches: ["main"] #chạy khi có lệnh push lên nhánh main

  pull_request:
    branches: ["main"] #chạy khi hành động tạo pull request vào nhánh main

# Khai báo các công việc (jobs) cần thực hiện trong workflow
jobs:
  #building: Job thứ nhất có thể đặt tên khác, nhưng cần đảm bảo tên này duy nhất trong workflow
  # Job thứ nhất: Kiểm tra cú pháp và build thử Docker image (Giai đoạn CI)
  building:
    runs-on: ubuntu-latest # Chạy trên máy chủ ảo Ubuntu mới nhất do GitHub cung cấp

    steps:
      # Bước 1: Tải source code của repository về máy ảo GitHub Actions
      - name: Checkout code
        uses: actions/checkout@v4

      # Bước 2: Kiểm tra xem file docker-compose.yml có viết đúng cú pháp hay không
      - name: Check Docker Compose
        run: docker compose config

      # Bước 3: Chạy thử lệnh build Docker image để đảm bảo code không bị lỗi biên dịch/đóng gói
      - name: Build Docker images
        run: docker compose build
      
  # Job thứ hai: Tự động triển khai lên AWS EC2 (Giai đoạn CD)
  deploy:
    if: github.event_name == 'push' # Chỉ chạy job này khi sự kiện là push code thực tế (bỏ qua khi tạo pull request)
    needs: building                # Phải đợi job "building" chạy thành công hoàn toàn thì job này mới được chạy
    runs-on: ubuntu-latest         # Chạy trên môi trường máy ảo Ubuntu của GitHub

    steps:
      # Bước 1: Tải source code của repository về máy ảo một lần nữa
      - name: Checkout code
        uses: actions/checkout@v4

      # Bước 2: Sử dụng giao thức bảo mật SCP qua SSH để copy toàn bộ source code lên máy chủ AWS EC2
      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}         # Địa chỉ IP của EC2 (lấy từ GitHub Secrets)
          username: ${{ secrets.VPS_USERNAME }} # Tên đăng nhập VPS, mặc định là ubuntu
          key: ${{ secrets.VPS_SSH_KEY }}       # Khóa bảo mật RSA (.pem) để kết nối SSH an toàn
          source: "."                           # Copy toàn bộ thư mục gốc của project
          target: "/home/ubuntu/app"            # Thư mục đích sẽ lưu code trên máy chủ EC2

      # Bước 3: Kết nối SSH vào máy chủ EC2 để thực hiện lệnh vận hành ứng dụng bằng Docker
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/ubuntu/app          # Di chuyển vào thư mục chứa source code vừa copy lên
            sudo docker compose down     # Tắt và xóa các container cũ đang chạy để dọn dẹp tài nguyên
            sudo docker compose up -d --build # Tự động build lại image mới và khởi động lại toàn bộ hệ thống ở chế độ ngầm (-d)